function tentativaerro(dataframe)

x = data

end